version: '3.1'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./banco.sql:/docker-entrypoint-initdb.d/banco.sql
    environment:
      MYSQL_ROOT_PASSWORD: mysql

  app:
    image: ghcr.io/robsonandradev/node-app:latest
    ports:
      - 8080:3000
    restart: always
